Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = 'k8s-dev'
  config.vm.define vm_name = 'k8s'

  config.vm.provision "shell", privileged: false, path: "../scripts/install_minikube.sh"

  config.vm.network :private_network, ip: "172.17.8.111"
  config.vm.provider :hyperv do |v|
      v.cpus = 2
	  v.memory = 3096
  end
end
